### ISSUE TITLE
Issue on Menma

### ISSUE THREAD

**Issue by Mousukoshi3d** [tera-private-toolbox/library#1]
Hey, some players got an issue on Menma since library got updated is it possible to have previous version of library ? Sending screenshot 
![library](https://github.com/tera-private-toolbox/library/assets/103002476/d78cffb8-f6c2-4345-ba89-1ff563ecb3a3)

**Comment by pimpmyalpaca** [comment]
I too have been getting this issue ever since the start of today.

**Comment by justkeepquiet** [comment]
Menma's Toolbox is not supported by latest version of Library, you need to use Private Toolbox: https://github.com/tera-private-toolbox/tera-toolbox

**Comment by justkeepquiet** [comment]
If you want to use Menma's toolbox, you need to ask him to add the opcode "S_CHANGE_RELATION" to his toolbox.
Private Toolbox has a full set of opcodes, so such a issue will not arise when using it.

**Comment by justkeepquiet** [comment]
Temporarily fixed https://github.com/tera-private-toolbox/library/commit/0cb7392f6fbedc308490099d9af858060126ef61
